apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-front
  namespace: nikhil
  labels:
    app: nginx-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-front
  template:
    metadata:
      labels:
        app: nginx-front
    spec:
      containers:
      - name: pod-nginx-front
        image: nikkytub1/ngnxf:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /ready
            port: 80
            httpHeaders:
            - name: CC-Ready
              value: Frontend
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
            httpHeaders:
            - name: CC-Ready
              value: Frontend
          initialDelaySeconds: 15
          periodSeconds: 3
