apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-back
    test: liveness
  name: liveness-http-back
  namespace: nikhil
spec:
  containers:
  - name: liveness-back
    image: cnych/liveness:latest
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /ready
        port: 80
        httpHeaders:
        - name: CC-Ready
          value: Backend
      initialDelaySeconds: 3
      periodSeconds: 3