apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-front
    test: readiness
  name: readiness-http-front
  namespace: nikhil
spec:
  containers:
  - name: readiness-front
    image: oomk8s/readiness-check:2.0.1
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /ready
        port: 80
        httpHeaders:
        - name: CC-Ready
          value: Frontend
      initialDelaySeconds: 3
      periodSeconds: 3