apiVersion: v1
kind: Service
metadata:
  name: cc-backend-service
  namespace: nikhil
  labels:
    app: nginx-back
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx-back
