apiVersion: v1
kind: Service
metadata:
  name: cc-frontend-service
  namespace: nikhil
  labels:
    app: nginx-front
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: nginx-front
